In [56]:
import pandas as pd #work with data as tables
import numpy as np #work wiht numbers as matracies
import matplotlib.pyplot as plt
import tensorflow as tf


In [57]:
#Step1 load data

dataframe = pd.read_csv('data.csv') #dataframe object (obj create to memory)
#removed the features we don't care about
dataframe = dataframe.drop(['index', 'price', 'sq_price'], axis=1)
#we only us the first 10 rows
dataframe = dataframe[0:10]
dataframe

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [58]:
#step 2 - add labels Remmeber, this is a classification problem !
#1 is good buy and 0 us bad buy
dataframe.loc[:,('y1')] = [1,1,1,0,0,1,0,1,1,1]
#y2 is a negation of y1, opposite
dataframe.loc[:,('y2')] = dataframe['y1'] == 0
#turn TRUE/FALSE values to 1s and 0s
dataframe.loc[:, ('y2')] = dataframe['y2'].astype(int)
dataframe

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [59]:
#Stemp 3 - prepare data for tensorflow (tesnors)
#btw tensors are a generic version of vectors and matrices
#vector is a list of numbers
#matrix is a list of list of numbers (2D tensor)
#list of list of list of numbers (3D tensor)
#....
#convert features to input tensor
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
#convert labels to input tensors
inputY = dataframe.loc[:, ['y1', 'y2']].as_matrix()

In [60]:
inputX

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00],
       [1.534e+03, 3.000e+00],
       [1.427e+03, 3.000e+00],
       [1.380e+03, 3.000e+00],
       [1.494e+03, 3.000e+00]])

In [61]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [62]:
#step 4 - write out our hyperparameters
#learning rate means hwo fast we reach convergence
learning_rate = 0.000001
training_epochs = 2000 #how many times we train
display_step = 50 #how often to display the process of training
n_samples = inputY.size


In [63]:
#Step 5 - Create our computation graph/neural network
#for feature input tensors, None means any numbers of examples, 2 is the side of the input tensor (2 features)
#placeholders are gateways for data into our computation graph
x = tf.placeholder(tf.float32, [None, 2])

#create weights
#2x2 float matrix, that we ll keep updating through the training process
#variables in tf hold and update parameters
#in memory buffers containing tensors
W = tf.Variable(tf.zeros([2,2]))

#add biases (example is b in y = mx +b , b is the bias, like that) //looks like a hiden layer but not the same check the vid photo
b = tf.Variable(tf.zeros([2]))

#multiply our weights by our inputs, first calculation
#weights are how we govern how data flows in our computation graph
#multiply input by weights and add biases
y_values = tf.add(tf.matmul(x, W), b)

#apply softmax to value we just created
#softmax is ouractivation function
y = tf.nn.softmax(y_values)

#feed in a matrix of labels
y_ = tf.placeholder(tf.float32, [None, 2])

In [64]:
# step 6 perform training
#create our cost function, mean squared error
#reduce sum computes the sum of elements across dimensions of a tensor
cost = tf.reduce_sum(tf.pow(y_ - y,2))/(2*n_samples)

#Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [65]:
#initialize variables and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)


In [71]:
#training loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY})
    
    #write out logs of training
    if (i) % display_step ==0:
        cc = sess.run(cost, feed_dict={x: inputX, y_ : inputY})
        print ("Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc))

print ("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print ("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')





Training step: 0000 cost= 0.114958666
Training step: 0050 cost= 0.109539948
Training step: 0100 cost= 0.109539881
Training step: 0150 cost= 0.109539807
Training step: 0200 cost= 0.109539740
Training step: 0250 cost= 0.109539665
Training step: 0300 cost= 0.109539606
Training step: 0350 cost= 0.109539531
Training step: 0400 cost= 0.109539464
Training step: 0450 cost= 0.109539405
Training step: 0500 cost= 0.109539330
Training step: 0550 cost= 0.109539263
Training step: 0600 cost= 0.109539188
Training step: 0650 cost= 0.109539129
Training step: 0700 cost= 0.109539054
Training step: 0750 cost= 0.109538995
Training step: 0800 cost= 0.109538913
Training step: 0850 cost= 0.109538853
Training step: 0900 cost= 0.109538786
Training step: 0950 cost= 0.109538712
Training step: 1000 cost= 0.109538652
Training step: 1050 cost= 0.109538570
Training step: 1100 cost= 0.109538510
Training step: 1150 cost= 0.109538451
Training step: 1200 cost= 0.109538391
Training step: 1250 cost= 0.109538309
Training ste

In [72]:
sess.run(y, feed_dict = {x: inputX})

array([[0.7112522 , 0.2887478 ],
       [0.66498977, 0.33501023],
       [0.73657656, 0.26342347],
       [0.6471879 , 0.3528121 ],
       [0.78335613, 0.2166439 ],
       [0.70069474, 0.29930523],
       [0.6586633 , 0.34133676],
       [0.6482863 , 0.35171372],
       [0.6436828 , 0.35631716],
       [0.65480113, 0.3451989 ]], dtype=float32)

In [73]:
#its saying all houses are a good buy 7/10
#how to improve? add a hidden layer

#Btw, this is how I calculated the softmax values in the post:
sess.run(tf.nn.softmax([1., 2.]))

array([0.26894143, 0.7310586 ], dtype=float32)

SyntaxError: invalid syntax (<ipython-input-74-b5eb579e8848>, line 1)